config/routes.rb
LimHouse::Application.routes.draw do
  
  resources :users
  resources :sessions, only:[:new,:create,:detroy]
  resources :products
  resources :auctions
  resources :clients
  #resources :prod_returns
  resources :prod_returns do
    member do
      put 'change_status'
    end
  end
  resources :comments


  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  match '/prod_returns/show_edit', to: 'prod_returns#show_edit'
  match '/prod_returns/group_delete', to: 'prod_returns#group_delete'
  match '/prod_returns/group_delete_att', to: 'prod_returns#group_delete_att'
  match '/prod_returns_archive', to: 'prod_returns#archive'
  match '/prod_returns/delete_att', to: 'prod_returns#delete_att'
  match '/prod_returns/send_backup', to: 'prod_returns#send_backup'

  match '/search', to: 'prod_returns#search'


  root :to => 'static_pages#home'
  #get "static_pages/home"
  match '/help', to: 'static_pages#help'

  #match '/signup', to:'users#new'

  # Sample of regular route:
  #   match 'products/:id' => 'catalog#view'
  # Keep in mind you can assign values other than :controller and :action

  # Sample of named route:
  #   match 'products/:id/purchase' => 'catalog#purchase', :as => :purchase
  # This route can be invoked with purchase_url(:id => product.id)

  # Sample resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Sample resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Sample resource route with more complex sub-resources
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', :on => :collection
  #     end
  #   end

  # Sample resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  # root :to => 'welcome#index'

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'
end

app/views/shared/_attachment_link.html.erb
<% if (prod_return.prattachments.length>0) %>
	<% if (prod_return.prattachments.length > 1) %>
		<button id="addAttmnt<%=prod_return.id%>" data-html="true" type="button" class="popover<%=prod_return.id%> btn" data-toggle="popover" data-placement="left" title="Zalaczniki" data-content='<div class="container span5"><%= render partial:"shared/files_popover", collection: prod_return.prattachments %></div>'><span class="glyphicon glyphicon-th-large"></button>
		<script type="text/javascript">
		$(document).ready(function() {
		  $(".popover<%=prod_return.id%>").popover();
		});
	</script>
	<% else %>
		<%= link_to( prod_return.prattachments[0].pr_file.url, target: "_blank", id:"attmnt#{prod_return.id}") do%>
			<div style="color: rgb(50,50,50)" ><span class="glyphicon glyphicon-picture icon_small"></span></div>
		<% end %>
	<% end %>
<% else %>
	<button id="addAttmnt<%=prod_return.id%>" data-html="true" type="button" class="popover<%=prod_return.id%> btn btn-small" data-toggle="popover" data-placement="left" title="Wybiez plik" data-content='<%= render partial:"shared/file_form_popover", locals:{prod_return:prod_return}%>', disabled>Dadaj zalacznik</button>
	<script type="text/javascript">
		$(document).ready(function() {
		  $(".popover<%=prod_return.id%>").popover();
		});
	</script>	
<% end %>

app/views/shared/_comments_modal.html.erb
<button class="btn btn-small comment" data-toggle="modal" data-target=<%= "#myModal#{prod_return.id}_#{tab}" %> id=<%="btn_comment#{prod_return.id}"%>>
 <span class="glyphicon glyphicon-comment"></span> <%= "#{prod_return.comments[0].content[0..23]}..." %>
</button>
<div class="modal hide" id=<%= "myModal#{prod_return.id}_#{tab}" %> tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h5 class="modal-title" id="myModalLabel">Komentarze</h5>
      </div>
      <div class="modal-body">
			<ol> <%= render partial: 'comments/comment', collection: prod_return.comments %></ol>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
	<div id="error_explanation">
		<div class="alert alert-error">
			The form contains <%= pluralize(object.errors.count, "error") %>.
		</div>
		<ul>
			<% object.errors.full_messages.each do |msg| %>
			<li>* <%= msg %></li>
			<% end %>
		</ul>
	</div>
<% end %>

app/views/shared/_file_form_popover.html.erb
<%= form_for prod_return, :html => { :multipart => true } do |f| %>
	<%= file_field_tag "files[]", type: :file, multiple: true %>
	<%= submit_tag 'OK', class:'btn btn-success btn-small', id:"file_submit#{prod_return.id}"%>
<% end %>

app/views/shared/_files_popover.html.erb
<div class="span1 word-wrap">
<div class="file_thumbs">
	<% if (files_popover.pr_file.content_type == 'application/pdf') %>
		<%= link_to( files_popover.pr_file.url, :target => "_blank")  do %>
			<div style="color: rgb(50,50,50)" ><span class="glyphicon glyphicon-file icon_small"></span></div>
		<% end %>
	<% else %>
		<%= link_to(image_tag(files_popover.pr_file.url(:thumb)), files_popover.pr_file.url, :target => "_blank")  %>
	<% end %>
	<br>
</div>
<div class="small1"> <%= files_popover.pr_file_file_name %> </div>
</div>

app/views/shared/_status_modal.html.erb
<button class="btn btn-small" data-toggle="modal" data-target=<%= "#change_status#{prod_return.id}_#{tab}"%> id=<%="changeStatus#{prod_return.id}"%> >
  Zmien status
</button>
<div class="modal hide" id="<%="change_status#{prod_return.id}_#{tab}"%>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h5 class="modal-title" id="myModalLabel">
			<%= form_for(prod_return, url: change_status_prod_return_path(prod_return)) do |f|%>
        	Zmień status z <%= "#{ApplicationHelper::ReturnsStatus.key(prod_return.status)}" %> na <%= f.select :status, options_for_select(ApplicationHelper::ReturnsStatus.keys.to_a.map {|z| [z]}, next_status(prod_return.status)), {}, {id:"#{tab}select#{prod_return.id}", onchange:"updateCommentMsg('#{tab}select#{prod_return.id}', '#{tab}content#{prod_return.id}')"} %>
        </h5>
      </div>
      <div class="modal-body">
      		<%= fields_for prod_return.comments.build do |c|%>
				<%= c.text_area :content, value:generate_status_message(prod_return.status), :rows => 4, :style => 'width: 90%', id:"#{tab}content#{prod_return.id}", oninput:"textLengthLimit('#{tab}content#{prod_return.id}','#{tab}textLength#{prod_return.id}','200')" %> <div id=<%="#{tab}textLength#{prod_return.id}"%>></div>
			<% end %>
      </div>
      <div class="modal-footer">
      	<button type="button" class="btn btn-default" data-dismiss="modal">Anuluj</button>
      		<%= f.hidden_field :ret, value:prod_return.id %>
      		<%= f.hidden_field :user_id, value:current_user.id %>
          <%= f.submit "Gotowe", class:"btn btn-default btn-success", id:"changeStatusOK#{prod_return.id}" %>
      		<% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_tab_table.html.erb
<table class="table table-bordered td">
<tr>
	<th> 
		<div class="btn-group center">
		<button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown"><%= check_box_tag("check_action") %> <span class="caret"></span>
		</button>
		<ul class="dropdown-menu" role="menu">
			<li class="check_all"><a href="#">Wszystkie</a></li>
			<li class="check_none"><a href="#">Żadne </a></li>
		</ul>
		</div>
	 </th>
	<th><div class="center">#</div></th>
	<th><div class="center">Tytuł aukcji</div></th>
	<th><div class="center">Klient</div></th>
	<th><div class="center">Data transakcji</div></th>
	<th><div class="center">Data zwrotu</div></th>
	<th><div class="center">Status</div></th>
	<th><div class="center">Komentarze</div></th>
	<th><div class="center">Zmień status</div></th>
	<th><div class="center">Załącznik</div></th>
</tr>
<%= render partial: 'prod_returns/prod_return', collection: returns, locals: {tab:tab} %>
</table>
<%= will_paginate returns %>

app/views/shared/_tools_top.html.erb
<div class="pull-right">
	<div class="btn-toolbar" role="toolbar">
		<div class="btn-group">
			<div hidden class="tools">
				<div class="btn-group">
					<%= link_to("#", class: "btn btn-default tools_edit_group", id:"tools_show") do%>
						<span class="glyphicon glyphicon-list-alt"></span> Pokaż
					<% end %>
					<%= link_to("#", class: "btn btn-default btn-success tools_edit_group", id:"tools_edit") do%>
						<span class="glyphicon glyphicon-edit"></span> Edytuj
					<% end %>
				</div>
				<div class="btn-group">
					<%= link_to("#", class: "btn btn-default btn-danger tools-delete", id:"tools_delete", title:"Usuń zaznaczone zwroty") do%>
						<span class="glyphicon glyphicon-trash"></span>
					<% end %>
					<%= link_to("#", class: "btn btn-default btn-warning ", title:"Usuń zaznaczone załączniki", disabled:true) do%>
						<span class="glyphicon glyphicon-trash"></span> <span class="glyphicon glyphicon-picture"></span>
					<% end %>
				</div>
			</div>
		</div>
		<div class="btn-group">
			<%= form_tag("/search", method: "get", remote:true, class:"btn-toolbar", id:"search_form") do %>
				<span class="search_field" hidden>
				<%= text_field_tag(:q, nil, class:"btn-toolbar") %>
			<% end %>
		</div>
			<%= link_to("#", class: "btn btn-default btn-info btn-wide", id:"tools_search", title:"Wyszukaj zwroty") do%>
				<span class="glyphicon glyphicon-search"></span>
			<% end %>
		<div class="btn-group">
			<span><%= link_to "Dodaj nowy ticket zwrotu", new_prod_return_path, class: "btn btn-primary" %></span>
		</div>
	</div>
</div>