config/routes.rb
LimHouse::Application.routes.draw do
  
  resources :users
  resources :sessions, only:[:new,:create,:detroy]
  resources :products
  resources :auctions
  resources :clients
  #resources :prod_returns
  resources :prod_returns do
    member do
      put 'change_status'
    end
  end
  resources :comments


  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  match '/prod_returns/show_edit', to: 'prod_returns#show_edit'
  match '/prod_returns/group_delete', to: 'prod_returns#group_delete'
  match '/prod_returns/group_delete_att', to: 'prod_returns#group_delete_att'
  match '/prod_returns_archive', to: 'prod_returns#archive'
  match '/prod_returns/delete_att', to: 'prod_returns#delete_att'
  match '/prod_returns/send_backup', to: 'prod_returns#send_backup'

  match '/search', to: 'prod_returns#search'


  root :to => 'static_pages#home'
  #get "static_pages/home"
  match '/help', to: 'static_pages#help'

  #match '/signup', to:'users#new'

  # Sample of regular route:
  #   match 'products/:id' => 'catalog#view'
  # Keep in mind you can assign values other than :controller and :action

  # Sample of named route:
  #   match 'products/:id/purchase' => 'catalog#purchase', :as => :purchase
  # This route can be invoked with purchase_url(:id => product.id)

  # Sample resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Sample resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Sample resource route with more complex sub-resources
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', :on => :collection
  #     end
  #   end

  # Sample resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  # root :to => 'welcome#index'

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'
end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :description, :price, :status, :title, :quantity, :image_lnk, :web_link
  has_many :auctions, dependent: :destroy

  validates :title, :description, :price, :status, :quantity, presence: true
  validates :title, length: {maximum: 50}
  validates :quantity, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :price, :format => { :with => /\A\d+(?:\.\d{0,2})?\z/ }, :numericality => {:greater_than => 0}
  validates :status,  inclusion: { in: ProductsHelper::Product_status.values } 
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	#before_filter signed_in_user

  def new
  	@product = Product.new
  end

  def create
  	@product = Product.new(params[:product])
  	@product.status = 1
  	if @product.save
  		flash[:success] = "New product added"
  		redirect_to root_path
  	else
  		flash.now[:error] = "adding unsuccessful"
  		render 'new'
  	end
  end

  def show
  	@prod = Product.find(params[:id])
  end

  def edit
  	@product = Product.find(params[:id])
  end

  def update
  	@product = Product.find(params[:id])

    #cos to malo eleganckie moze pasuje before save zrobic 
    if params[:product][:quantity].to_i > 0
      params[:product][:status] = 1
    end
  	if @product.update_attributes(params[:product])
  		flash[:success] = "Zmiany zostaly wprowadzone"
  		redirect_to @product
  	else
  		flash.now[:error] = "Zmiany nie zostaly wprowadzone"
  		render 'edit'
  	end
  end

  def destroy
    Product.find(params[:id]).destroy
    flash[:notice] = "Produkt usuniety"
    redirect_to root_path
  end
end

app/helpers/products_helper.rb
module ProductsHelper
	Product_status = {clean: 0, not_auctioned: 1}.freeze
end

app/views/products/_product.html.erb
<li class="product_list">
	<div class="panel panel-default">
		<div class="panel-heading">
			<div class="edit-products">
				<%= link_to 'Edit', edit_product_path(product) %> |
				<%= link_to 'Delete', product, method: :delete, confirm: "You sure?" %>
			</div>
			<h5 class="panel-title"><%= link_to "#{product.title}", product_path(product) %></h5>
			<% if product.quantity > 0 %>
				<%= link_to "Auction", {:controller => 'auctions', :action => 'new', :product_id => product.id} %>
			<% end %>
		</div>
		<div class="panel-body">
			<div class="product-thumbnail">
				<%= image_tag image_link_for(product), width:"100", height:"auto" %>
			</div>
			<div class="span8">
	    		<%= simple_format(shorten_description(product.description)) %>
	    	</div>
    		<div class="product-listing-side">
				<span><strong> Price: <%= product.price %></strong></span><br>
				<span>Ilość: <%= product.quantity %></span>
			</div>
		</div>
	</div>
</li>

app/views/products/edit.html.erb
<% provide(:title,'Edit product') %>

<h2> Edit product page </h2>

<div class="row new_product_form">
	<div class="offset2 span9">
		<%= form_for @product do |f|%>
			
			<%= render 'shared/error_messages', object: f.object %>

			<%= f.label :Title %>
			<%= f.text_field :title %>
			<%= f.label :Cena %>
			<%= f.text_field :price %>
			<%= f.label :Ilość %>
			<%= f.number_field :quantity %>
			<%= f.label :Status %>
			<%= f.select  :status, options_for_select(ProductsHelper::Product_status.to_a.map { |z| [z[0].to_s,z[1]] }) %>
			<%= f.label :Image %>
			<%= f.text_field :image_lnk %>
			<%= image_tag image_link_for(@product), width: 100, height: "auto", id:'img_id', class:'img_class'%>
			<%= f.label :Opis %>
			<%= f.text_area :description, :rows => 7, :style => 'width: 95%' %>
			<span class="input-group-btn"> <%= submit_tag("Submit") %> </span>
		<% end %>
	</div>
</div>

app/views/products/new.html.erb
<% provide(:title,"Add new product") %>

<h3>Add new product</h3>

<div class="new_product_form">
<div class="row">
<div class="span4">
<%= form_for @product do |f| %>
	<%= render 'shared/error_messages', object: f.object %>
	<div class="input-group">
		 <span>Title: </span>
		<%= f.text_field :title %>
	</div>
	<div class="input-group">
		 <span>Price: </span>
		<%= f.text_field :price %>
	</div>
	<div class="input-group">
		 <span >Quantity: </span>
		<%= f.number_field :quantity %>
	</div>
	<div class="input-group">
		 <span >Image link: </span>
		<%= f.url_field :image_lnk %>
	</div>
	<div class="span9">
		<%= f.label "Description" %>
		<%= f.text_area :description, :rows => 7, :style => 'width: 95%' %>
		<span class="input-group-btn"> <%= submit_tag("Submit") %> </span>
	</div>
<% end %>
</div>
</div>
</div>

app/views/products/show.html.erb
<% provide(:title, "#{@prod.title}") %>

<h2> Product info page </h2>
<h3> Produkt: <%= @prod.title %> </h3>
<br>
<section>
	<div class="row">
		<div class="span4">
			<div class="image-container">
				<%= image_tag image_link_for(@prod)%><br>
				Cena: <%= @prod.price %><br>
				Status: <%= ProductsHelper::Product_status.key(@prod.status) %><br>
				Ilość: <%= @prod.quantity %><br>
				<%= link_to "Edit", edit_product_path(@prod) %> | 
				<%= link_to 'Delete', @prod, method: :delete, confirm: "You sure?" %>
			</div>
		</div>
		<div class="span8">
			<aside>
				Opis: 
				<section class ="center">
					<%= simple_format(@prod.description) %><br>
				</section>
			</aside>	
		</div>
	</div>
</section>