config/routes.rb
LimHouse::Application.routes.draw do
  
  resources :users
  resources :sessions, only:[:new,:create,:detroy]
  resources :products
  resources :auctions
  resources :clients
  #resources :prod_returns
  resources :prod_returns do
    member do
      put 'change_status'
    end
  end
  resources :comments


  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  match '/prod_returns/show_edit', to: 'prod_returns#show_edit'
  match '/prod_returns/group_delete', to: 'prod_returns#group_delete'
  match '/prod_returns/group_delete_att', to: 'prod_returns#group_delete_att'
  match '/prod_returns_archive', to: 'prod_returns#archive'
  match '/prod_returns/delete_att', to: 'prod_returns#delete_att'
  match '/prod_returns/send_backup', to: 'prod_returns#send_backup'

  match '/search', to: 'prod_returns#search'


  root :to => 'static_pages#home'
  #get "static_pages/home"
  match '/help', to: 'static_pages#help'

  #match '/signup', to:'users#new'

  # Sample of regular route:
  #   match 'products/:id' => 'catalog#view'
  # Keep in mind you can assign values other than :controller and :action

  # Sample of named route:
  #   match 'products/:id/purchase' => 'catalog#purchase', :as => :purchase
  # This route can be invoked with purchase_url(:id => product.id)

  # Sample resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Sample resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Sample resource route with more complex sub-resources
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', :on => :collection
  #     end
  #   end

  # Sample resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  # root :to => 'welcome#index'

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'
end

app/views/layouts/_footer.html.erb
<footer class="footer">
	<small>
		<a href="http://rails.org/"> rails </a> test
	</small>
	<nav>
		<ul>
			<li><%= link_to "About",'#' %></li>
			<li><%= link_to "Contact", '#' %></li>
			<li><a href="http://news.railstutorial.org/">News</a></li>
		</ul>
	</nav>
</footer>
<br>
<%= link_to image_tag("rails.png", alt: "Rails"), 'http://rubyonrails.org/'%>

app/views/layouts/_header.html.erb
<header class="navbar navbar-inverse navbar-fixed-top">
	<div class="navbar-inner">
		<div>
			<%= link_to "Products mini-manager", root_path, id: "logo" %>
			<nav>
				<ul class="nav pull-right">
					<li><%= link_to "Home", root_path %></li>
					<% if signed_in? %>
						<li><%= link_to "Archive", prod_returns_archive_path %></li>
						<li id="fat-menu" class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown">Account <b class="caret"></b></a>
							<ul class="dropdown-menu">
								<li><%= link_to "User", current_user %></li>
								<li class="divider"></li>
								<li><%= link_to "Logout", signout_path, method: "delete" %></li>
							</ul>
						</li>
					<% else %>
						<li><%= link_to "Sign in", signin_path %></li>
					<% end %>
				</ul>
			</nav>
		</div>
	</div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
		<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap-glyphicons.css" rel="stylesheet">
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>

<body>
	<div class="container-fluid">
		<%= render 'layouts/header' %>
	
		<% flash.each do |key, value| %>
			<div class="alert alert-<%= key %>"><%= value %></div>
		<% end %>
		<div class="row">
			<div>
				<%= yield %>
			</div>
		</div>
		<% render 'layouts/footer' %>
		<%= debug(params) if Rails.env.development? %>
	</div>


<script type="text/javascript">

function textLengthLimit(id_source, id_target, limit) {
	var tmp;
	var text;
    tmp = limit - document.getElementById(id_source).value.length
    if (tmp > 0) {
    	text = "pozostalo "+tmp;
    }else {
    	text = "tekst jest za dlugi o "+ Math.abs(tmp);
    }
    document.getElementById(id_target).innerHTML = text;
}

function updateCommentMsg(id_source, id_target) {
	var tmp;
	var text;
    tmp = document.getElementById(id_source).value;
    if (tmp == "przyjete") {
    	text = "Oczekiwanie na przesyłkę, przekazane dalej";
    }else if (tmp == "przetworzone") {
    	text = "Przesylka dotarla, wszystko sie zgadza. Czeka na wyslanie";
    }else if (tmp == "wyslane") {
    	text = "Przesylka wyslana";
    }else if (tmp == "zamknij_usun") {
    	text = "Zwrot zamkniety i usuniety";
    }else if (tmp == "zwrot_gotowki") {
      text = "Przesylka dotarla, czeka na wyslanie gotowki";
    }else if (tmp == "wymiana") {
      text = "Przesylka dotarla. Czeka na wyslanie wymiany";
    }else {
      text = "Zwrot zamkniety i przeniesiony do archiwum"
    }
    document.getElementById(id_target).value = text;
}
</script>
</body>
</html>